[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[omspy]
name = "omspy"
version = "0.11.0"
description = ""
authors = ["darkseid <uberdeveloper001@gmail.com>"]
readme = "README.md"
packages = [{include = "omspy"}]

